# The URL the site will be built for
base_url = "https://mmestiyak.com"

# The title of your site
title = "Meer's Log"

# The description of your site
description = "A simple home on the internet. Software developer, cyclist, boxer, and agro enthusiast."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Whether to generate feeds
generate_feeds = true

# The taxonomies to be rendered for the site
taxonomies = [
    { name = "tags" },
    { name = "categories" }
]

# Default language for search indexing (important for non-English content)
default_language = "en"

# Search configuration
[search]
index_format = "elasticlunr_javascript"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Enable footnotes
footnote_anchor_prefix = ""

# Enable tables
enable_implicit_figures = true

[extra]
# Put all your custom variables here
